### ISSUE TITLE
Yang parser accepts yang schema without proper curly bracket closing 

### ISSUE THREAD

**Issue by ahassany** [yang-central/yangkit#11]
I've tried using the yang parser on the following schema that is missing three closing curly brackets (leaf definition closing, container definition closing, and module closing). Yang parser parses and validate it correctly without throwing any errors?

```
module a-module {
  yang-version 1.1;
  namespace "urn:example:a-module";
  prefix a;

  organization
    "Test Organization";
  contact
    "Ahmed Elhassany <mailto:ahmed.elhassany@swisscom.com>";
  description
    "Simple Test module with one typedef and a container of one leaf";
  reference
    "testing";

  revision 2023-02-01 {
    reference
      "first revision";
  }

  typedef aType {
    type int8;
    description
      "Simple int8 type for testing";
  }

  container x {
    description
      "Test container";
    leaf aLeaf {
      type aType;
      description
        "Example leaf";
```

The test code I used was
```java
package yang.test;

import org.yangcentral.yangkit.common.api.validate.ValidatorResult;
import org.yangcentral.yangkit.model.api.schema.YangSchemaContext;
import org.yangcentral.yangkit.parser.YangYinParser;

public class TestCase {
  public static void main(String[] args) throws Exception{
    YangSchemaContext yang = YangYinParser.parse("~/yangdir");
    ValidatorResult result = yang.validate();
    if (result.isOk()) {
      System.out.println("Yang Schema is valid, number of modules read is: " + yang.getModules().size());
    } else {
      System.out.println("Yang Schema is NOT valid, number of modules read is: " + yang.getModules().size());
    }
  }
}

```

And the output was `Yang Schema is valid, number of modules read is: 1`. I don't this is a correct behavior by yangkit: I was expecting this value to be invalid. FYI, pyang and libyang won't accept this schema as a valid one.

**Comment by lllyfeng** [comment]
It's obviously a big bug. this code worked well for many years. But I modified it several months ago for optimizing some functions.  Thank you, I will fix it quickly.



________________________________

冯冲 Feng Chong
Mobile: +86-13776612983
Email: ***@***.***

发件人：Ahmed Elhassany ***@***.***>
收件人：yang-central/yangkit ***@***.***>
抄 送：Subscribed ***@***.***>
时 间：2023-02-17 18:18:39
主 题：[yang-central/yangkit] Yang parser accepts yang schema without proper curly bracket closing (Issue #11)


I've tried using the yang parser on the following schema that is missing three closing curly brackets (leaf definition closing, container definition closing, and module closing). Yang parser parses and validate it correctly without throwing any errors?

module a-module {
  yang-version 1.1;
  namespace "urn:example:a-module";
  prefix a;

  organization
    "Test Organization";
  contact
    "Ahmed Elhassany ***@***.***>";
  description
    "Simple Test module with one typedef and a container of one leaf";
  reference
    "testing";

  revision 2023-02-01 {
    reference
      "first revision";
  }

  typedef aType {
    type int8;
    description
      "Simple int8 type for testing";
  }

  container x {
    description
      "Test container";
    leaf aLeaf {
      type aType;
      description
        "Example leaf";


The test code I used was

package yang.test;

import org.yangcentral.yangkit.common.api.validate.ValidatorResult;
import org.yangcentral.yangkit.model.api.schema.YangSchemaContext;
import org.yangcentral.yangkit.parser.YangYinParser;

public class TestCase {
  public static void main(String[] args) throws Exception{
    YangSchemaContext yang = YangYinParser.parse("~/yangdir");
    ValidatorResult result = yang.validate();
    if (result.isOk()) {
      System.out.println("Yang Schema is valid, number of modules read is: " + yang.getModules().size());
    } else {
      System.out.println("Yang Schema is NOT valid, number of modules read is: " + yang.getModules().size());
    }
  }
}

And the output was Yang Schema is valid, number of modules read is: 1. I don't this is a correct behavior by yangkit: I was expecting this value to be invalid. FYI, pyang and libyang won't accept this schema as a valid one.

**Comment by ahassany** [comment]
Thank you, it would really beneficial to invest some time in tests to avoid major regressions like that.

**Comment by lllyfeng** [comment]
This issue has been resolved. please update code.
