### ISSUE TITLE
Enhance the YangYinParser API to work with none file-based yang sources

### ISSUE THREAD

**Issue by ahassany** [yang-central/yangkit#12]
Currently, the `YangYinParser` provides 8 public methods for parsing YANG schemas, all of which are File or Directory based. This represents a tight coupling to the filesystem and can limit the usage of this API inside other libraries that don't save the schema on a traditional file system. 

Is there any futures plans to refactor this API and decouple `YangYinParser` from how the yang schemas are stored?

The current, API
1. `public static YangSchemaContext parse(List<File> yangFiles)`
2. `public static YangSchemaContext parse(File yangDir)`
3. `public static YangSchemaContext parse(File yangDir, YangSchemaContext context)`
4. `public static YangSchemaContext parse(String yangDir)`
5. `public static YangSchemaContext parse(String yangDir, String dependency, String capabilities)`
6. `public static YangSchemaContext parse(String yangDir, String capabilities)`
7. `public static YangSchemaContext parse(String yangDir, YangSchemaContext context)`
8. `public static YangSchemaContext parse(List<File> files, YangSchemaContext context)`

**Comment by lllyfeng** [comment]
Thank you. What are you expect? Inputstream?url?




________________________________

冯冲 Feng Chong
Mobile: +86-13776612983
Email: ***@***.***

发件人：Ahmed Elhassany ***@***.***>
收件人：yang-central/yangkit ***@***.***>
抄 送：Subscribed ***@***.***>
时 间：2023-02-17 23:14:18
主 题：[yang-central/yangkit] Enhance the YangYinParser API to work with none file-based yang sources (Issue #12)


Currently, the YangYinParser provides 8 public methods for parsing YANG schemas, all of which are File or Directory based. This represents a tight coupling to the filesystem and can limit the usage of this API inside other libraries that don't save the schema on a traditional file system.

Is there any futures plans to refactor this API and decouple YangYinParser from how the yang schemas are stored?

The current, API

  1.  public static YangSchemaContext parse(List<File> yangFiles)
  2.  public static YangSchemaContext parse(File yangDir)
  3.  public static YangSchemaContext parse(File yangDir, YangSchemaContext context)
  4.  public static YangSchemaContext parse(String yangDir)
  5.  public static YangSchemaContext parse(String yangDir, String dependency, String capabilities)
  6.  public static YangSchemaContext parse(String yangDir, String capabilities)
  7.  public static YangSchemaContext parse(String yangDir, YangSchemaContext context)
  8.  public static YangSchemaContext parse(List<File> files, YangSchemaContext context)

**Comment by ahassany** [comment]
Yes, `InputStream` could a good fit

**Comment by lllyfeng** [comment]
@ahassany I have added some APIs to support parsing YANG from inputstream. expect your opinion about this.
  /**
    * parse YANG module from inputStream, not import-only
    * @param inputStream
    * @param moduleInfo
    * @param context
    * @return
    * @throws YangParserException
    * @throws IOException
    * @throws DocumentException
    */

   public static YangSchemaContext parse(InputStream inputStream,
                                         String moduleInfo,
                                         YangSchemaContext context)
           throws YangParserException, IOException, DocumentException;

   /**
    * parse YANG/YIN module from inputStream
    * @param inputStream  the candidate input stream
    * @param moduleInfo  the description of the module, it often indicates the position information and module information
    *                    for example, "ftp://10.1.1.1/ietf-interfaces@2019-07-31"
    *                    or "C:\documents\yang\ietf-interfaces@2019-07-31.yang"
    * @param isYang
    * @param importOnly
    * @param context
    * @return
    * @throws YangParserException
    * @throws IOException
    * @throws DocumentException
    */
   public static YangSchemaContext parse(InputStream inputStream,
                                         String moduleInfo,
                                         boolean isYang,
                                         boolean importOnly,
                                         YangSchemaContext context)
           throws YangParserException, IOException, DocumentException;

**Comment by marcosbis** [comment]
Hi, is this implemented already somehow?

Thanks

**Comment by lllyfeng** [comment]
Yes, it has been implemented.

**Comment by marcosbis** [comment]
can you please provide sample to implement from String ? the javadoc dont seems to be working and can't find any example
Thanks

**Comment by lllyfeng** [comment]
@marcosbis I add some examples in README.md of yangkit-parser module. Is it enough for you?
