### ISSUE TITLE
Nested `while (true)`

### ISSUE THREAD

**Issue by ahassany** [yang-central/yangkit#15]
There are two nested `while(true)` statements at line https://github.com/yang-central/yangkit/blob/main/yangkit-model-impl/src/main/java/org/yangcentral/yangkit/model/impl/stmt/ModuleImpl.java#L794

I tried to understand the code, but I couldn't tell why these two loops are there. Is that correct and I'm missing something or this code can be simplified a bit?

**Comment by lllyfeng** [comment]
This code has been optimized. Please update code.
