### ISSUE TITLE
javadoc links are not working

### ISSUE THREAD

**Issue by balazsbme** [yang-central/yangkit#19]
Hi all,

I found your project very interesting, I would like to take a look at the documentation to find minimal examples for parsing YANG model, generating YANG instance data, etc.

But the javadoc links are not working, pointing to not found links. Are you planning to fix this issue?

Thanks,
Balazs

**Comment by lllyfeng** [comment]
Hi Balazs,
   Welcome,:) I have fixed this issue, now the javadoc works.
